version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: ancestry_mongo
    environment:
      MONGO_INITDB_DATABASE: ancestry_db
    ports:
      - "27017:27017"
    volumes:
      - C:/Users/netaj/mongodata:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mongo_data: 